swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get all user transactions for the current month
      description: Returns all transactions for the authenticated user, grouped by account, for the current month.
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: List of transactions grouped by account
          schema:
            $ref: '#/definitions/TransactionListResponse'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  /user/transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get details of a specific transaction
      description: Returns detailed information for a specific transaction belonging to the authenticated user.
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: transactionId
          description: ID of the transaction
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Transaction details
          schema:
            $ref: '#/definitions/TransactionResponse'
        '404':
          description: Transaction not found
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  /user/transactions/{transactionId}/notes/{noteId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get a specific note for a transaction
      description: Returns a specific note for a transaction.
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: transactionId
          description: ID of the transaction
          required: true
          type: string
        - in: path
          name: noteId
          description: ID de la note
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Note details
          schema:
            $ref: '#/definitions/Note'
        '404':
          description: Note not found
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
    post:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Add a note to a transaction
      description: Add a new note to a transaction.
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: transactionId
          description: ID of the transaction
          required: true
          type: string
        - in: path
          name: noteId
          description: ID de la note
          required: true
          type: string
        - in: body
          name: body
          description: Note à ajouter
          required: true
          schema:
            $ref: '#/definitions/Note'
      produces:
        - application/json
      responses:
        '201':
          description: Note added
          schema:
            $ref: '#/definitions/Note'
        '400':
          description: Invalid fields
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
    patch:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Partially update a transaction
      description: Partially update information for a specific transaction.
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: transactionId
          description: ID of the transaction
          required: true
          type: string
        - in: path
          name: noteId
          description: ID de la note
          required: true
          type: string
        - in: body
          name: body
          description: Transaction partial update payload
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdate'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction updated successfully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid fields
        '404':
          description: Transaction not found
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Delete a transaction
      description: Delete a specific transaction.
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: transactionId
          description: ID of the transaction
          required: true
          type: string
        - in: path
          name: noteId
          description: ID de la note
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Transaction deleted successfully
        '404':
          description: Transaction not found
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Note:
    type: object
    properties:
      noteId:
        type: string
        description: Identifiant unique de la note
      content:
        type: string
        description: Contenu de la note
  Transaction:
    description: Represents a single banking transaction.
    type: object
    properties:
      id:
        type: string
        description: Unique identifier for the transaction
      accountId:
        type: string
        description: Identifier of the account related to the transaction
      date:
        type: string
        format: date
        description: Date of the transaction
      amount:
        type: number
        description: Amount of the transaction
      type:
        type: string
        description: Transaction type (e.g. debit, credit)
      category:
        type: string
        description: Category of the transaction
      notes:
        type: array
        description: Tableau de notes associées à la transaction
        items:
          type: object
          properties:
            noteId:
              type: string
              description: Identifiant unique de la note
            content:
              type: string
              description: Contenu de la note

  TransactionListResponse:
    description: Response model for a list of transactions grouped by account.
    type: object
    properties:
      status:
        type: integer
        description: Status code of the response
      message:
        type: string
        description: Informational message
      body:
        type: object
        description: Contains the grouped transactions
        properties:
          accounts:
            type: array
            description: List of accounts with their transactions
            items:
              type: object
              properties:
                accountId:
                  type: string
                  description: Identifier of the account
                transactions:
                  type: array
                  description: Transactions for the account
                  items:
                    $ref: '#/definitions/Transaction'

  TransactionResponse:
    description: Response model for a single transaction detail.
    type: object
    properties:
      status:
        type: integer
        description: Status code of the response
      message:
        type: string
        description: Informational message
      body:
        $ref: '#/definitions/Transaction'


  TransactionUpdate:
    description: Payload model for updating an existing transaction.
    type: object
    properties:
      date:
        type: string
        format: date
        description: New date of the transaction
      amount:
        type: number
        description: New amount of the transaction
      type:
        type: string
        description: New transaction type (e.g. debit, credit)
      category:
        type: string
        description: New category of the transaction
      notes:
        type: array
        description: Nouveau tableau de notes pour la transaction
        items:
          type: object
          properties:
            noteId:
              type: string
              description: Identifiant unique de la note
            content:
              type: string
              description: Contenu de la note
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
